apiVersion: v1
kind: Secret
metadata:
  name: order-service
  namespace: order
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}