server:
  error:
    include-stacktrace: never

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
        session-token: ${AWS_SESSION_TOKEN}
      region:
        static: ${AWS_REGION:us-west-2}
      sqs:
        enabled: true
        auto-create: false
        listener:
          auto-startup: false
        queue:
          auto-create: false
        queue-attributes:
          enabled: false
      sns:
        enabled: true
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order}
    username: ${DB_USER:admin}
    password: ${DB_PASS:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-replacement: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    filter: true
    persist-authorization: true

security:
  jwt:
    jwks-uri: ${SECURITY_JWT_JWKS_URI:http://localhost:8080/.well-known/jwks.json}
    audience: ${SECURITY_JWT_AUDIENCE:fast-food-api}
    algorithm: ${SECURITY_JWT_ALGORITHM:RS256}

app:
  messaging:
    order-payments-topic: ${ORDER_PAYMENTS_TOPIC_ARN:arn:aws:sns:us-west-2:082727220338:order-payments}
    default-payment-method: ${ORDER_PAYMENTS_METHOD:PIX}
    payment-status-queue: ${PAYMENT_STATUS_QUEUE_NAME:payment-status-queue}
  services:
    customer-url: ${CUSTOMER_SERVICE_URL:http://0.0.0.0:8000}
    product-url: ${PRODUCT_SERVICE_URL:http://0.0.0.0:8000}

management:
  endpoints:
    web:
      exposure:
        include: "health"
