apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service
  namespace: soat-orders
data:
  # --- Service Discovery (Comunicação Interna no Cluster) ---
  CUSTOMER_SERVICE_URL: "http://api.soat-customers.svc.cluster.local"
  PRODUCT_SERVICE_URL:  "http://api.soat-products.svc.cluster.local"

  # --- Configuração de Banco de Dados (RDS) ---
  SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

  # --- AWS Config ---
  AWS_REGION: "us-west-2"
  AWS_SNS_ENDPOINT: ""
  AWS_SQS_ENDPOINT: ""

  ORDER_PAYMENTS_TOPIC_ARN: "${ORDER_PAYMENTS_TOPIC_ARN}"